#!/bin/bash

sudo tar cfz backup.tar.gz /etc
 
find backup.tar.gz -mtime -1 -type f -print &> /dev/null

if [ $? -eq 0 ]
    then
    echo
    echo Backup was created
    echo
    echo Archiving Backup
    # scp /tmp/backup.tar.gz root@ip-address/path
    else
    echo Backup failed
fi