#!/bin/bash
# iNightjar

hosts="/home/inightjar/ConTainer/codehub/BashScripts/CheckServersConnectivity/hosts" # hosts absolute path

for ip in $(cat $hosts)

do
    ping -c1 $ip &> /dev/null
    if [ $? -eq 0 ]
    then
    echo $ip is OK
    else
    echo $ip is NOT OK
    fi
done


