#!/bin/bash
# iNightjar

hosts="" # absolute path of the hosts

for ip in $(cat $hosts)

do
    ping -c1 $ip &> /dev/null
    if [ $? -eq 0 ]
    then
    echo $ip is OK
    else
    echo $ip is NOT OK
    fi
done


